version: "3"
services:
  master:
    environment:
      - SECONDARIES_NAMES=secondary,secondary2
    build:
      context: .
      dockerfile: master.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5100:8000"
  
  secondary:
    build:
      context: .
      dockerfile: secondary.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5200:8000"

  secondary2:
    build:
      context: .
      dockerfile: secondary.Dockerfile
    volumes:
      - .:/app/
    ports:
      - "5300:8000"
